In [78]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.8.2


In [79]:
vector = tf.constant([1, 2])
vector.ndim, vector

(1, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [80]:
matrix = tf.constant([[3, 4],
                     [5, 6]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6]], dtype=int32)>, 2)

In [81]:
tf.random.set_seed(42)
random_tensor = tf.random.uniform(shape=[10,10])
random_tensor.ndim, tf.shape(random_tensor), tf.size(random_tensor)

(2,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=100>)

In [82]:
one_tensor = tf.ones(shape=[5,300])
one_tensor

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)>

In [83]:
zero_tensor = tf.zeros(shape=[5,300])
zero_tensor

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [84]:
tf.random.set_seed(42)
tensor_one = tf.random.uniform(minval=0, maxval=1, shape=(5,300), seed=42, dtype=tf.dtypes.float16)
tensor_one

<tf.Tensor: shape=(5, 300), dtype=float16, numpy=
array([[0.3525 , 0.2207 , 0.5645 , ..., 0.09863, 0.617  , 0.1807 ],
       [0.2471 , 0.5117 , 0.1895 , ..., 0.835  , 0.95   , 0.288  ],
       [0.1475 , 0.4238 , 0.0928 , ..., 0.704  , 0.992  , 0.6143 ],
       [0.7246 , 0.547  , 0.9766 , ..., 0.1602 , 0.548  , 0.5195 ],
       [0.925  , 0.9033 , 0.1279 , ..., 0.874  , 0.9434 , 0.8896 ]],
      dtype=float16)>

In [85]:
tf.random.set_seed(44)
tensor_two = tf.random.uniform(minval=0, maxval=1, shape=(5,300), seed=44, dtype=tf.dtypes.float16)
tensor_two

<tf.Tensor: shape=(5, 300), dtype=float16, numpy=
array([[0.2256 , 0.5244 , 0.3418 , ..., 0.3066 , 0.2314 , 0.1982 ],
       [0.7686 , 0.02344, 0.2158 , ..., 0.62   , 0.843  , 0.1914 ],
       [0.1875 , 0.7383 , 0.09863, ..., 0.954  , 0.04883, 0.295  ],
       [0.2676 , 0.00879, 0.885  , ..., 0.207  , 0.715  , 0.8857 ],
       [0.2998 , 0.3281 , 0.421  , ..., 0.9414 , 0.11914, 0.2305 ]],
      dtype=float16)>

In [86]:
first_result=tf.matmul(tf.transpose(tensor_one), tensor_two)
first_result


<tf.Tensor: shape=(300, 300), dtype=float16, numpy=
array([[0.7686, 0.6094, 1.219 , ..., 1.422 , 0.9253, 1.016 ],
       [0.9395, 0.742 , 1.092 , ..., 1.753 , 1.001 , 0.959 ],
       [0.5903, 0.4192, 1.161 , ..., 0.7017, 1.009 , 1.069 ],
       ...,
       [1.101 , 0.88  , 0.793 , ..., 2.076 , 0.979 , 0.7305],
       [1.484 , 1.393 , 1.395 , ..., 2.727 , 1.495 , 1.3   ],
       [0.783 , 0.8516, 1.019 , ..., 1.765 , 0.792 , 0.9375]],
      dtype=float16)>

In [87]:
second_result = tf.matmul(tensor_one, tf.transpose(tensor_two))
second_result

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[67.06, 80.4 , 75.9 , 72.4 , 73.4 ],
       [68.9 , 81.1 , 78.2 , 77.06, 81.3 ],
       [66.3 , 79.6 , 73.7 , 74.06, 72.  ],
       [69.5 , 79.06, 74.7 , 75.2 , 78.  ],
       [72.56, 83.44, 78.9 , 78.  , 77.75]], dtype=float16)>

In [88]:
tensor_one @ tf.transpose(tensor_two)

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[67.06, 80.4 , 75.9 , 72.4 , 73.4 ],
       [68.9 , 81.1 , 78.2 , 77.06, 81.3 ],
       [66.3 , 79.6 , 73.7 , 74.06, 72.  ],
       [69.5 , 79.06, 74.7 , 75.2 , 78.  ],
       [72.56, 83.44, 78.9 , 78.  , 77.75]], dtype=float16)>

In [89]:
tf.tensordot(tf.transpose(tensor_one), tensor_two, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float16, numpy=
array([[0.7686, 0.6094, 1.219 , ..., 1.422 , 0.9253, 1.016 ],
       [0.9395, 0.742 , 1.092 , ..., 1.753 , 1.001 , 0.959 ],
       [0.5903, 0.4192, 1.161 , ..., 0.7017, 1.009 , 1.069 ],
       ...,
       [1.101 , 0.88  , 0.793 , ..., 2.076 , 0.979 , 0.7305],
       [1.484 , 1.393 , 1.395 , ..., 2.727 , 1.495 , 1.3   ],
       [0.783 , 0.8516, 1.019 , ..., 1.765 , 0.792 , 0.9375]],
      dtype=float16)>

In [90]:
tensor_three= tf.random.uniform(minval=0, maxval=1, shape=[224,224,3], dtype=tf.dtypes.float16, seed=42)
tensor_three

<tf.Tensor: shape=(224, 224, 3), dtype=float16, numpy=
array([[[0.3828 , 0.3486 , 0.05566],
        [0.6514 , 0.0752 , 0.2598 ],
        [0.3809 , 0.663  , 0.2305 ],
        ...,
        [0.379  , 0.3135 , 0.1855 ],
        [0.0742 , 0.786  , 0.7314 ],
        [0.3955 , 0.8037 , 0.4727 ]],

       [[0.6807 , 0.67   , 0.7393 ],
        [0.918  , 0.371  , 0.4238 ],
        [0.871  , 0.1338 , 0.675  ],
        ...,
        [0.915  , 0.0654 , 0.5957 ],
        [0.373  , 0.966  , 0.166  ],
        [0.459  , 0.709  , 0.4258 ]],

       [[0.6797 , 0.707  , 0.784  ],
        [0.09375, 0.2148 , 0.957  ],
        [0.6514 , 0.2305 , 0.7783 ],
        ...,
        [0.662  , 0.9307 , 0.714  ],
        [0.3242 , 0.92   , 0.1416 ],
        [0.2441 , 0.0332 , 0.6885 ]],

       ...,

       [[0.3682 , 0.3965 , 0.02734],
        [0.715  , 0.9463 , 0.798  ],
        [0.872  , 0.1572 , 0.5615 ],
        ...,
        [0.09375, 0.4395 , 0.249  ],
        [0.702  , 0.2656 , 0.1641 ],
        [0.02148, 0.900

In [91]:
tf.reduce_min(tensor_three).numpy(), tf.reduce_max(tensor_three).numpy()

(0.0, 0.999)

In [92]:
tf.random.set_seed(45)
tensor_four = tf.random.uniform(shape=[1,224,224,3], seed= 45)
tensor_four

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.08154094, 0.3302691 , 0.27059197],
         [0.18059897, 0.96229947, 0.03738379],
         [0.4458009 , 0.06841433, 0.8138174 ],
         ...,
         [0.00676239, 0.50290394, 0.971967  ],
         [0.46122265, 0.03852546, 0.84263813],
         [0.30829334, 0.5983435 , 0.08025968]],

        [[0.147964  , 0.01208651, 0.60910773],
         [0.05100822, 0.078444  , 0.66665435],
         [0.69258666, 0.15790021, 0.2569716 ],
         ...,
         [0.8793608 , 0.35932016, 0.69881177],
         [0.9259553 , 0.99136627, 0.08638167],
         [0.12600505, 0.06342709, 0.71989954]],

        [[0.14405847, 0.3751676 , 0.08720517],
         [0.43162656, 0.08500147, 0.7028973 ],
         [0.08930051, 0.08162451, 0.80287313],
         ...,
         [0.74183285, 0.45342445, 0.34239018],
         [0.06846499, 0.18082082, 0.41872025],
         [0.3072089 , 0.9232222 , 0.9889084 ]],

        ...,

        [[0.86688495, 0.01441157, 

In [93]:
tf.squeeze(tensor_four).shape

TensorShape([224, 224, 3])

In [94]:
tf.random.set_seed(66)
tensor_five=tf.constant(tf.random.uniform(shape=[10],dtype=tf.dtypes.float16,seed=66))
tensor_five

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([0.582  , 0.999  , 0.0537 , 0.1846 , 0.05566, 0.839  , 0.1406 ,
       0.1748 , 0.6846 , 0.1748 ], dtype=float16)>

In [95]:
print ("The Aggression of tensor_five : \n")
print ("The minimum of tensor_five :"             , tf.reduce_min(tensor_five).numpy())
print ("The maximum of tensor_five :"             , tf.reduce_max(tensor_five).numpy())
print ("The mean of tensor_five :"                , tf.reduce_mean(tensor_five).numpy())
print ("The sum of tensor_five :"                 , tf.reduce_sum(tensor_five).numpy())
print ("The variance of tensor_five :"            , tf.math.reduce_variance(tensor_five).numpy())
print ("The standard deviation of tensor_five :"  , tf.math.reduce_std(tensor_five).numpy())
print ("The position of min value in tensor_five : \n" , tf.argmin(tensor_five))
print ("The position of max value in tensor_five : \n" , tf.argmax(tensor_five))
print ("The position of min value in tensor_five with np.argmin:" , np.argmin(tensor_five))
print ("The position of max value in tensor_five with np.argmax:" , np.argmax(tensor_five))

The Aggression of tensor_five : 

The minimum of tensor_five : 0.0537
The maximum of tensor_five : 0.999
The mean of tensor_five : 0.389
The sum of tensor_five : 3.889
The variance of tensor_five : 0.1118
The standard deviation of tensor_five : 0.3345
The position of min value in tensor_five : 
 tf.Tensor(2, shape=(), dtype=int64)
The position of max value in tensor_five : 
 tf.Tensor(1, shape=(), dtype=int64)
The position of min value in tensor_five with np.argmin: 2
The position of max value in tensor_five with np.argmax: 1


In [97]:
tensor_six = tf.constant ([1,2,3,4,5,6,7,8,9,10])
tensor_six

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [98]:
tf.one_hot(tensor_six, depth=10, on_value="ture", off_value="false")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'false', b'ture', b'false', b'false', b'false', b'false',
        b'false', b'false', b'false', b'false'],
       [b'false', b'false', b'ture', b'false', b'false', b'false',
        b'false', b'false', b'false', b'false'],
       [b'false', b'false', b'false', b'ture', b'false', b'false',
        b'false', b'false', b'false', b'false'],
       [b'false', b'false', b'false', b'false', b'ture', b'false',
        b'false', b'false', b'false', b'false'],
       [b'false', b'false', b'false', b'false', b'false', b'ture',
        b'false', b'false', b'false', b'false'],
       [b'false', b'false', b'false', b'false', b'false', b'false',
        b'ture', b'false', b'false', b'false'],
       [b'false', b'false', b'false', b'false', b'false', b'false',
        b'false', b'ture', b'false', b'false'],
       [b'false', b'false', b'false', b'false', b'false', b'false',
        b'false', b'false', b'ture', b'false'],
       [b'false', b'fal