# **In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow**

More specifically, wer are going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up your regular Python Functions)
* Usiiing GPUs with TensorFlow (or TPUs)
* Exercses to fro yourself!!

## **Introducton to Tensors**
* import and check gpu
* Create tensors with `tf.constant`
* Create tensors with `tf.variable`
* Create random tensor with `tf.random`
* Shuffle the tensor with `tf.random.shuffle`
* Other ways to make tensor with `tf.ones` , `tf.zeros`
* Trun numpy array into tensor 

### **Import and check gpu**

In [1]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.1


In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



### **Create tensors with tf.constant**

In [ ]:
#Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the dimension of our vector

vector.ndim

1

In [ ]:
#Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant ([[10.,7.],
                               [3.,2.],
                               [8.,9.]], dtype= tf.float16) # specify data type with dtype parameter
      
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What is the number of dimensions of another matrix
another_matrix.ndim

2

In [ ]:
#Let's create a tensor

tensor = tf.constant([
                      [[ 1, 2, 3,],
                        [ 4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
#Dimension of  Tensors

tensor.ndim

3

What we have created so far::

* Scalar : a single number
* vector: a number with direction (e.g wind speed and direction)
* Matrix : a 2-dimensional array of numbers
* Tensor : an n - dimensional array of numbers (where n can be any number,
     a 0 - dimensional tensor is a scalar,
     a 1 - dimensional tensor is a vector.
     a 2 - dimensional tensor is a matrix.

### **Creating  Tensors with 'tf.Variable**



In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# Create the smae ensor with tf.Variable() as above

changeable_tensor = tf.Variable ([10, 7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor

#changeable_tensor[0] = 7
#changeable_tensor

In [ ]:
# How about we try .assign()

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change our unchangble tensor

#unchangeable_tensor[0].assign(7) 
#unchangeable_tensor

### **Creating random tensors**

Random tensors are tensors of some abitrary size which contain random numbers.

In [ ]:
# Create two random tensors (but the same) with same tensors

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2
random_3 = tf.random.Generator.from_seed(4)
random_3 = random_3.normal(shape=(3, 2))
random_3


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.0019137 ,  0.6735137 ],
       [ 0.06987712, -1.4077919 ],
       [ 1.0278524 ,  0.27974114]], dtype=float32)>

In [ ]:
#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
random_1, random_3, random_1 == random_3

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### **Shuffle the order of elements in a tensor with tf.random.shuffle** 

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)

not_shuffled = tf.constant([[10, 7],
                              [3, 4],
                              [2, 5]])
not_shuffled.ndim 
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

:

In [ ]:
not_shuffled_1 = tf.constant([[1, 2],
                              [3, 4],
                              [5, 6]])
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
not_shuffled_2 = tf.constant([[7, 8],
                              [9, 20],
                              [11,12]])
tf.random.shuffle(not_shuffled_2,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 20],
       [11, 12]], dtype=int32)>

In [ ]:
not_shuffled_3 = tf.constant([[10, 7],
                              [3, 4],
                              [2, 5],
                              [1, 2],
                              [3, 4],
                              [5, 6],
                              [7, 8],
                              [9, 20],
                              [11,12]])

tf.random.set_seed(42)
tf.random.shuffle(not_shuffled_3, seed=42)


<tf.Tensor: shape=(9, 2), dtype=int32, numpy=
array([[ 1,  2],
       [10,  7],
       [ 7,  8],
       [ 5,  6],
       [ 9, 20],
       [ 2,  5],
       [11, 12],
       [ 3,  4],
       [ 3,  4]], dtype=int32)>

In [ ]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'
print(tf.random.uniform([1]))  # generates 'A3'
print(tf.random.uniform([1]))  # generates 'A4'

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)
tf.Tensor([0.7402308], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'


tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'


tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'


(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [ ]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'


tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.4243431], shape=(1,), dtype=float32)
tf.Tensor([0.92531705], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'


tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [ ]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'


(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6087816], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)


### **Other  ways to make tensors** 

In [ ]:
#Create a tensor of all ones
#two dimensional array => test_tetnsors=tf.ones([7,3])
#three dimensiional array | 

test_tensors=tf.ones([2 , 5, 4, 3])

In [ ]:
test_tensors, test_tensors.ndim

(<tf.Tensor: shape=(2, 5, 4, 3), dtype=float32, numpy=
 array([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],
 
 
        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
   

In [ ]:
#Create a tensor of all zeroes
tf.zeros([4,3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### **Turn NumPy arrays into tensors**

The Main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numberical Computing).

In [ ]:
#You can also turn NumPy arrays into tensors
import numpy as np 
numpy_A = np.arange(1, 25, dtype=np.int32) # create numpy array between 1 and 25

numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensors
# y = tf.constant( vector ) # non-captital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant( numpy_A, shape=(2, 3, 4) )
B = tf.constant( numpy_A)
C = tf.constant( numpy_A, shape=(3, 8))
D = tf.constant( numpy_A, shape=(2, 2, 3, 2))
A, B, C, D, A.ndim, B.ndim, C.ndim, D.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 9, 10],
          [11, 12]]],
 
 
        [[[13, 14],
          [15, 16],
          [17, 18]],
 
         [[19, 20],
          [21, 22],
          [23, 24]]]], dtype=int32)>,
 3,
 1,
 2,
 4)

## **Getting informatin from tensors**
* Shape -> `tf.shape`
* Rank  -> `tf.ndim`
* Aixs or dimension
* Size  -> `tf.size(tensor)`
* indexing tensor with `:`

### **When dealing with tensors you probably want to be aware of the following attriubtes:**
* Shape -> `tf.shape`
* Rank  -> `tf.ndim`
* Aixs or dimension
* Size  -> `tf.size(tensor)`

In [ ]:
D, tf.size(D)

(<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 9, 10],
          [11, 12]]],
 
 
        [[[13, 14],
          [15, 16],
          [17, 18]],
 
         [[19, 20],
          [21, 22],
          [23, 24]]]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=24>)

In [ ]:
#Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
matrix= tf.zeros(shape=(3,4))
matrix

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


### **Indexing tensors**

Tensors can be indexed just like Python lists (choosing with `:`)

In [ ]:
some_list= [1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
A[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int32)>

In [ ]:
some_list[:1]

[1]

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
#Get the first element each dimension from each index except for the final one

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor ( 2 dimensions)

rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])

rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [ ]:
#Get the last item of each of our rank 2 tensor

rank_2_tensor[: , -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis= 0) #expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

## **Manipulating tensors (tensor operations)**

* Basic Operations (`+`, `-` , `*`, `/`)
* Matrix multiplication (`tf.matmul`, `tf.tensordot`, `@`)
* Dot product and example
* transpose (`tf.transpose`) , reshape (`tf.reshape`)



### **Basic operations**  
`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator

tensor = tf.constant ([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchange

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Substraction if you want 

tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use teh tensorflow built-in function too (have many adventages)

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### **Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations. 

There are two rules our tensors (or matrixes) need to fullful if we're going to matrix multiply them:

1. The inner dimesions must match 
2. The resulting matrix has the shape of the outer dimensions

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor # it is wrong because it is element wise and direct

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Example to multiply two tensors

tensor_1 = tf.constant([[1, 2, 5],
                        [7, 2, 1],
                        [3, 3, 3]])

tensor_2 = tf.constant([[3, 5],
                        [6, 7],
                        [1, 8]])

tensor_1, tensor_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [ ]:
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Create a tensor (3,2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create a tensor (3,2)
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensors of same shape
#tf.matmul(X,Y)

In [ ]:
# Let's change teh shape of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X.shape,tf.reshape(Y, shape= (2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# Try to matrix multiply X by reshape Y
tf.matmul(X,tf.reshape(Y, shape= (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
X @ tf.reshape(Y, shape= (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(X, shape= (2,3)).shape, Y

(TensorShape([2, 3]), <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#Try change the shape of X instead of Y
tf.matmul(tf.reshape(X, shape= (2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# Can do teh same with transpose
X, tf.transpose(X), tf.reshape(X, shape= (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose rather than reshape

tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Apple , Cherry and Blueberry example 

In [ ]:
daily_fruit_produce = tf.constant([[13, 9, 7, 15],
                                  [8, 7, 4, 6],
                                  [6, 4, 0, 3]])
price_of_fruit = tf.constant([[3],
                              [4],
                              [2]])

daily_fruit_produce, price_of_fruit, 

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[13,  9,  7, 15],
        [ 8,  7,  4,  6],
        [ 6,  4,  0,  3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[3],
        [4],
        [2]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(price_of_fruit), daily_fruit_produce)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[83, 63, 37, 75]], dtype=int32)>

### **The dot product**

Matrix multiplication is also referred to as the dot product.  
You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#Perform matrix multiplication between X and Y (transposed)
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
#Perform matrix multiplication between X and Y (reshaped)
tf.tensordot(X, tf.reshape(Y,(2,3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print ("Normal Y: ")
print (Y, "\n")

print ("Y reshaped to (2,3): ")
print (tf.reshape(Y,(2, 3)), "\n")

print ("Y transposed: ")
print (tf.transpose(Y), "\n")

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



**Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satisify the matrix multiplicaiton rules.**

## **Changing the datatype of a tensor**
* `tf.cast(tensor, dtype=tf.float16)`

In [ ]:
# Create a new tensor with default datatype (float32)

B = tf.constant( [1.7, 7.4] )
B.dtype


tf.float32

In [ ]:
C = tf.constant( [7, 10] )
C.dtype

tf.int32

In [ ]:
tf.__version__

'2.8.2'

In [ ]:
# Change from float32 to float16 (reduce precision and take lower memory i.e. 16 bit of memory)

D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
E_float16 = tf.cast (E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

## **Aggregating tensors**

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.
* Get the minimum (`tf.reduce_min`)
* Get the maximum (`tf.reduce_max`)
* Get the mean of a tensor (`tf.reduce_mean`)
* Get the sum of a tensor (`tf.reduce_sum`)
* Get the variance of tensor (`tf.math.reduce_variance`)
* Get the std of tensor (`tf.math.reduce_std`)

In [ ]:
# Get the absolute values

F = tf.constant ( [-7, -10])
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(F)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### **Let's go through the following forms of aggregation:**

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Own work
F_float16 = tf.cast(F, dtype=tf.float16)
tf.minimum(C, F) , tf.maximum(C, F), tf.reduce_mean(F) , tf.reduce_mean(F_float16) , tf.reduce_sum(F)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-8>,
 <tf.Tensor: shape=(), dtype=float16, numpy=-8.5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-17>)

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
E_tensor = tf.constant (np.random.randint(0,100, size=50))
E_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([53, 65, 31, 47, 29, 32, 61, 75, 69, 66, 20, 90, 59,  6, 63, 11,  0,
        4, 16, 97, 32, 14, 28,  7, 58, 60, 83, 49, 30, 39, 51,  0, 14, 49,
       79, 65, 40, 73, 83, 24, 99, 98,  3, 35, 57, 81, 82, 38, 92, 73])>

In [ ]:
print("Datatype of every element:", E_tensor.dtype)
print("Number of dimensions (rank):",  E_tensor.ndim)
print("Shape of tensor:", E_tensor.shape)
print("Elements along the 0 axis:", E_tensor.shape[0])
print("Elements along the last axis:", E_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(E_tensor).numpy())

Datatype of every element: <dtype: 'int64'>
Number of dimensions (rank): 1
Shape of tensor: (50,)
Elements along the 0 axis: 50
Elements along the last axis: 50
Total number of elements in our tensor: 50


In [ ]:
print ("The Aggression of E_tensor : \n")
print ("The minimum of E_tensor :", tf.reduce_min(E_tensor))
print ("The maximum of E_tensor :", tf.reduce_max(E_tensor))
print ("The mean of E_tensor :"   , tf.reduce_mean(E_tensor))
print ("The sum of E_tensor :"    , tf.reduce_sum(E_tensor))

The Aggression of E_tensor : 

The minimum of E_tensor : tf.Tensor(0, shape=(), dtype=int64)
The maximum of E_tensor : tf.Tensor(99, shape=(), dtype=int64)
The mean of E_tensor : tf.Tensor(48, shape=(), dtype=int64)
The sum of E_tensor : tf.Tensor(2430, shape=(), dtype=int64)


In [ ]:
np.min(E_tensor) , np.max(E_tensor), np.mean(E_tensor), np.sum(E_tensor)

(0, 99, 48.6, 2430)

In [ ]:
E_tensor_float16 = tf.cast (E_tensor, dtype=tf.float16)
E_tensor_float16

<tf.Tensor: shape=(50,), dtype=float16, numpy=
array([53., 65., 31., 47., 29., 32., 61., 75., 69., 66., 20., 90., 59.,
        6., 63., 11.,  0.,  4., 16., 97., 32., 14., 28.,  7., 58., 60.,
       83., 49., 30., 39., 51.,  0., 14., 49., 79., 65., 40., 73., 83.,
       24., 99., 98.,  3., 35., 57., 81., 82., 38., 92., 73.],
      dtype=float16)>

In [ ]:
print ("The variance of E_tensor :"           , tf.math.reduce_variance(E_tensor_float16).numpy())
print ("The standard deviation of E_tensor :" , tf.math.reduce_std(E_tensor_float16).numpy())

The variance of E_tensor : 829.0
The standard deviation of E_tensor : 28.8


In [ ]:
#To find the variance of our tensor, there is another way by importing tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=828>

## **Find the positional maximum and minimum in one dimensional array (index of min and max value)**
* `tf.argmin`
* `tf.argmax`

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F_tensor = tf.random.uniform(shape=[50])
F_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
print("Datatype of every element:", F_tensor.dtype)
print("Number of dimensions (rank):",  F_tensor.ndim)
print("Shape of tensor:", F_tensor.shape)
print("Elements along the 0 axis:", F_tensor.shape[0])
print("Elements along the last axis:", F_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(F_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 1
Shape of tensor: (50,)
Elements along the 0 axis: 50
Elements along the last axis: 50
Total number of elements in our tensor: 50


In [ ]:
# Find the positional maximum
tf.argmax(F_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
np.argmax(F_tensor)

42

In [ ]:
# Index on our largest value position
F_tensor[tf.argmax(F_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of F_tensor
tf.reduce_max(F_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
F_tensor[tf.argmax(F_tensor)] == tf.reduce_max(F_tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the poisitional min value of F_tensor
tf.argmin(F_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using the positional minimum index
F_tensor[tf.argmin(F_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.reduce_min(F_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.reduce_min(F_tensor) == F_tensor[tf.argmin(F_tensor)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

## **Revision what I Learn**
* Big_A test
* Big_B test

### **Big_A test**

In [ ]:
tf.random.set_seed(42)
Big_A = tf.random.uniform(shape=[50,50,50])
Big_A

<tf.Tensor: shape=(50, 50, 50), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 , ..., 0.16461694,
         0.7381023 , 0.32054043],
        [0.6073899 , 0.46523476, 0.97803545, ..., 0.09517312,
         0.08617878, 0.6247839 ],
        [0.37050653, 0.5139042 , 0.6233207 , ..., 0.85811317,
         0.9377897 , 0.9186075 ],
        ...,
        [0.84568083, 0.83324707, 0.35982323, ..., 0.9763311 ,
         0.71534157, 0.80455256],
        [0.25784433, 0.88950765, 0.36271334, ..., 0.4969108 ,
         0.51945186, 0.7945261 ],
        [0.47140646, 0.48127735, 0.9360609 , ..., 0.5226487 ,
         0.37384737, 0.24491489]],

       [[0.3692348 , 0.28328001, 0.8914689 , ..., 0.6156374 ,
         0.40012956, 0.19048297],
        [0.04116869, 0.03733265, 0.696017  , ..., 0.24319911,
         0.01366436, 0.698539  ],
        [0.11048746, 0.91399777, 0.05517614, ..., 0.34117603,
         0.7157594 , 0.60382354],
        ...,
        [0.17039919, 0.22767663, 0.682515  , ..., 0.57

In [ ]:
print("Datatype of every element:", Big_A.dtype)
print("Number of dimensions (rank):",  Big_A.ndim)
print("Shape of tensor:", Big_A.shape)
print("Elements along the 0 axis:", Big_A.shape[0])
print("Elements along the last axis:", Big_A.shape[-1])
print("Total number of elements in our tensor:", tf.size(Big_A).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 3
Shape of tensor: (50, 50, 50)
Elements along the 0 axis: 50
Elements along the last axis: 50
Total number of elements in our tensor: 125000


In [ ]:
print ("The Aggression of Big_A : \n")
print ("The minimum of Big_A :"             , tf.reduce_min(Big_A).numpy())
print ("The maximum of Big_A :"             , tf.reduce_max(Big_A).numpy())
print ("The mean of Big_A :"                , tf.reduce_mean(Big_A).numpy())
print ("The sum of Big_A :"                 , tf.reduce_sum(Big_A).numpy())
print ("The variance of Big_A :"            , tf.math.reduce_variance(Big_A).numpy())
print ("The standard deviation of Big_A :"  , tf.math.reduce_std(Big_A).numpy())

The Aggression of Big_A : 

The minimum of Big_A : 3.5762787e-07
The maximum of Big_A : 0.999998
The mean of Big_A : 0.49896887
The sum of Big_A : 62371.11
The variance of Big_A : 0.0827708
The standard deviation of Big_A : 0.28769916


In [ ]:
print ("The position of min value in Big_A : \n" , tf.argmin(Big_A))
print ("The position of max value in Big_A : \n" , tf.argmax(Big_A))
print ("The position of min value in Big_A with np.argmin:" , np.argmin(Big_A))
print ("The position of max value in Big_A with np.argmax:" , np.argmax(Big_A))
### Because of 3 dimensional tensor, tf.argmin and np.argmin doesn't work and can find index of min value

The position of min value in Big_A : 
 tf.Tensor(
[[36 18 46 ... 27 38 30]
 [31 21 49 ... 22  1 13]
 [32 48 37 ... 41 19 34]
 ...
 [ 4 28 10 ...  7 14 47]
 [18 22 32 ... 20  9 12]
 [26 40 34 ... 40  3 40]], shape=(50, 50), dtype=int64)
The position of max value in Big_A : 
 tf.Tensor(
[[44 48 35 ... 42 39 42]
 [ 6 26 23 ... 26 22 17]
 [22  3 12 ... 15 49 49]
 ...
 [31 21 17 ...  0 26 42]
 [17 28 46 ...  6 22 13]
 [ 3 44 38 ... 27 19 11]], shape=(50, 50), dtype=int64)
The position of min value in Big_A with np.argmin: 80086
The position of max value in Big_A with np.argmax: 49209


### **Big_B test**

In [ ]:
tf.random.set_seed(42)
Big_B = tf.random.uniform(shape=[10,10])
Big_B

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
       [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
       [0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
       [0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ],
       [0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       [0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
        0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ],
       [0.28128064, 0.31513572, 0.60670924, 0.7498598 , 0.5016055 ,
        0.18282163, 0.13179815, 0.64636123, 0.9559475 , 0.66

In [ ]:
print ("Datatype of every element:"               , Big_B.dtype)
print ("Number of dimensions (rank):"             , Big_B.ndim)
print ("Shape of tensor:"                         , Big_B.shape)
print ("Elements along the 0 axis:"               , Big_B.shape[0])
print ("Elements along the last axis:"            , Big_B.shape[-1])
print ("Total number of elements in our tensor:"  , tf.size(Big_B).numpy())
print ("\n The Aggression of Big_B")
print ("The minimum of Big_B :"                   , tf.reduce_min(Big_B).numpy())
print ("The maximum of Big_B :"                   , tf.reduce_max(Big_B).numpy())
print ("The mean of Big_B :"                      , tf.reduce_mean(Big_B).numpy())
print ("The sum of Big_B :"                       , tf.reduce_sum(Big_B).numpy())
print ("The variance of Big_B :"                  , tf.math.reduce_variance(Big_B).numpy())
print ("The standard deviation of Big_B :"        , tf.math.reduce_std(Big_B).numpy())
print ("The position of min value in Big_B : \n"  , tf.argmin(Big_B))
print ("The position of max value in Big_B : \n"  , tf.argmax(Big_B))
print ("The position of min value in Big_B with np.argmin:" , np.argmin(Big_B))
print ("The position of max value in Big_B with np.argmax:" , np.argmax(Big_B))

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 2
Shape of tensor: (10, 10)
Elements along the 0 axis: 10
Elements along the last axis: 10
Total number of elements in our tensor: 100

 The Aggression of Big_B
The minimum of Big_B : 0.009463668
The maximum of Big_B : 0.97803545
The mean of Big_B : 0.50072575
The sum of Big_B : 50.072575
The variance of Big_B : 0.07598697
The standard deviation of Big_B : 0.27565733
The position of min value in Big_B : 
 tf.Tensor([8 3 2 9 0 6 1 9 9 1], shape=(10,), dtype=int64)
The position of max value in Big_B : 
 tf.Tensor([3 4 5 6 4 1 9 8 6 7], shape=(10,), dtype=int64)
The position of min value in Big_B with np.argmin: 16
The position of max value in Big_B with np.argmax: 52


In [ ]:
tf.argmin(Big_B) ### can't find position of mininum value bz of 2-dimensional array

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([8, 3, 2, 9, 0, 6, 1, 9, 9, 1])>

In [ ]:
X, tf.argmin(X), tf.reduce_min(X).numpy(), Y, tf.argmin(Y), tf.reduce_min(Y).numpy()

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>,
 1,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>,
 7)

In [ ]:
X[np.argmin(X),0] , np.argmin(X)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>, 0)

## **Other operation on tensor**
* Squeezing tensor `tf.squeeze`
* One-hot encoding tensors `tf.one_hot`


### **Squeezing a tensor (removing all single dimensions)**


In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant (tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### **One-hot encoding tensors**

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3]    # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding

tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

In [ ]:
tf.one_hot(some_list, depth=3, on_value="Ture", off_value="False")

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'Ture', b'False', b'False'],
       [b'False', b'Ture', b'False'],
       [b'False', b'False', b'Ture'],
       [b'False', b'False', b'False']], dtype=object)>

In [ ]:
tf.one_hot([10,9,8,7], depth=11)

<tf.Tensor: shape=(4, 11), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)>

## **Few others math operation**
* Squaring `tf.square` 
* log `tf.math.log`
* square root `tf.sqrt`, `tf.matrix_square_root`

### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root (will get error , method requires non-int data type  )
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
 tf.matrix_square_root(tf.cast(tensor, dtype=tf.float32)) 
 ## input must be 2x2 or equal dimensional tensor with float32

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.0125766, 1.4686388],
       [0.6294167, 1.7537433]], dtype=float32)>

In [ ]:
# log of H
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays.

In [ ]:
# Create a tensor directly from a NumPy array
J = tf.constant (np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tensor J to a NumPy array

J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy()[0]

3.0

In [ ]:
# The default types of each are slightly different

numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant ([3., 7., 10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## **Finding access to GPUs**


In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]